# Generated by Django 4.1 on 2024-11-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('installation', 'New Installation'), ('repair', 'Repair'), ('maintenance', 'Maintenance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
